# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGISSPT
                                 A QGIS plugin
 Calculate Land Surface Temperature (LST)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-12
        copyright            : (C) 2020 by Muhammad Rahmahalim
        email                : muhammad.rahmahalim@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGISSPT class from file QGISSPT.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .QGIS_SPT import QGISSPT
    return QGISSPT(iface)
